Traceback (most recent call last):
  File "/root/Group7-fall2024/optimal/bin/mutmut", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/root/Group7-fall2024/optimal/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Group7-fall2024/optimal/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/Group7-fall2024/optimal/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Group7-fall2024/optimal/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Group7-fall2024/optimal/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Group7-fall2024/optimal/lib/python3.12/site-packages/mutmut/__main__.py", line 1388, in results
    for path in walk_source_files():
  File "/root/Group7-fall2024/optimal/lib/python3.12/site-packages/mutmut/__main__.py", line 161, in walk_source_files
    for root, filename in walk_all_files():
  File "/root/Group7-fall2024/optimal/lib/python3.12/site-packages/mutmut/__main__.py", line 154, in walk_all_files
    for path in mutmut.config.paths_to_mutate:
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'paths_to_mutate'
